### ISSUE TITLE
No control after some time

### ISSUE THREAD

**Issue by schononas** [gruijter/com.gruijter.clusterlights#3]
Hi

After some time I can't control the light. If I restart Homey I can control the light again but the problem  is back after some time. When I try to control the light and have this problem I get the following error code:

2018-12-12 20:02:20 [err] [MyApp] unhandledRejection!  { Error: ACL Connection Already Exists (0xb)    at Object.JSON.parse (/opt/homey-client/system/helpers/jsonfns.js:1:1190)    at JSON.parse (<anonymous>)    at jsonToObject (/opt/homey-client/system/helpers/jsonfns.js:1:1083)    at function.e.data.map.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1379)    at Array.map (<anonymous>)    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1372)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emit (internal/child_process.js:762:12)    at _combinedTickCallback (internal/process/next_tick.js:142:11) message: 'ACL Connection Already Exists (0xb)' }

I tried to delete the device and then install it again but then I got this error right from the beginning:

2018-12-12 20:55:03 [log] [ManagerDrivers] [cluster_light] [0] TypeError: Cannot read property 'write' of undefined    at ClusterLightDevice.sendCommand (/drivers/cluster_light/device.js:111:21)    at <anonymous>    at process._tickCallback (internal/process/next_tick.js:189:7)
2018-12-12 20:55:03 [log] [ManagerDrivers] [cluster_light] [0] on/off requested: true

And after another reboot of the Homey I got this error: 2018-12-12 21:11:55 [log] [ManagerDrivers] [cluster_light] [0] { Error: Cannot read property 'getPeripheral' of undefined    at Object.JSON.parse (/opt/homey-client/system/helpers/jsonfns.js:1:1190)    at JSON.parse (<anonymous>)    at jsonToObject (/opt/homey-client/system/helpers/jsonfns.js:1:1083)    at function.e.data.map.e (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1379)    at Array.map (<anonymous>)    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1372)    at emitTwo (events.js:126:13)    at process.emit (events.js:214:7)    at emit (internal/child_process.js:762:12)    at _combinedTickCallback (internal/process/next_tick.js:142:11)  message: 'Cannot read property \\'getPeripheral\\' of undefined' }

I'm running firmware: 2.0.0-rc.2
And version of the app: v0.4.0

Happy for the app and just here to help you debug the app or if the problem is on my end, get the help I need! 👍

**Comment by gruijter** [comment]
Yeah, I noticed similar problems. BLE is still very buggy in Homey. I already implemented a number of workarounds to make it as stable as possible. I might be able to improve a little bit, but im not sure. We have to push Athom to improve ble if we want apps like this to work well.

Also, It seems you need to completely delete the app and reinstall to get rid of old config data.

Thx 4 the feedback anyway. Have to first address some other apps of mine. I hope tonfind some time this weekend to give this one another look at.

**Comment by gruijter** [comment]
should be fixed
